- hosts: wethinkcode
  become: true
  tasks:
    # https://stackoverflow.com/questions/33343215/how-to-get-an-arbitrary-remote-users-home-directory-in-ansible#33343455
    - name: Get user home directory
      getent:
        database: passwd
        key: "{{ user }}"
        split: ":"
    - name: Set user home variable
      set_fact:
        user_home: "{{ getent_passwd[user][4] }}"
    - name: Remove user home directory
      file:
        path: "{{ user_home }}"
        state: absent
    - name: Recreate user's home directory
      user:
        name: "{{ user }}"
        create_home: true
        state: present
    - name: Upload admin's public key
      authorized_key:
        user: "{{ user }}"
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/mphojele-personal
        - public_keys/mphojele-work
    - name: Recreate user's home xdg standard directories
      shell: "xdg-user-dirs-update --force"
      become: true
      become_user: "{{ user }}"
